### ISSUE TITLE
Make exception messages more descriptive for cases when test suites or flows are incorrectly disposed

### ISSUE THREAD

**Issue by boris-yakhno** [JetBrains/TeamCity.ServiceMessages#35]
### The problem

When `TeamCityTestSuiteBlock` or `TeamCityFlowWriter` instances are disposed, a check is made if no child suites/tests/flows are open. If there are open children, an exception is thrown. The exception message is not very descriptive, e.g.:
```
Some child test suite writers were not disposed.
System.InvalidOperationException
   at JetBrains.TeamCity.ServiceMessages.Write.Special.Impl.Writer.TeamCityTestSuiteBlock.DisposeImpl()
   at JetBrains.TeamCity.ServiceMessages.Write.Special.Impl.Writer.BaseDisposableWriter`1.Dispose()
   at JetBrains.TeamCity.ServiceMessages.Write.Special.Impl.TeamCityWriterImpl.Dispose()
...
```
which is not very useful to diagnose the problem.

### The proposal

The proposal is to add open suite / test / flow names to the exception message.

**Comment by boris-yakhno** [comment]
Hello @matt-richardson,

Could you please take a look at this PR and check that the changes in `TeamCityTestSuiteBlock.cs` will help with diagnosing the problem you described in #34?
